// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoTask.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ProtoTask_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ProtoTask_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ProtoTask_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ProtoTask_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ProtoTask_2eproto;
class EchoReq;
struct EchoReqDefaultTypeInternal;
extern EchoReqDefaultTypeInternal _EchoReq_default_instance_;
class IntIntProto;
struct IntIntProtoDefaultTypeInternal;
extern IntIntProtoDefaultTypeInternal _IntIntProto_default_instance_;
class ItemProto;
struct ItemProtoDefaultTypeInternal;
extern ItemProtoDefaultTypeInternal _ItemProto_default_instance_;
class LoginRequest;
struct LoginRequestDefaultTypeInternal;
extern LoginRequestDefaultTypeInternal _LoginRequest_default_instance_;
class LoginResponse;
struct LoginResponseDefaultTypeInternal;
extern LoginResponseDefaultTypeInternal _LoginResponse_default_instance_;
class LogoutRequest;
struct LogoutRequestDefaultTypeInternal;
extern LogoutRequestDefaultTypeInternal _LogoutRequest_default_instance_;
class LogoutResponse;
struct LogoutResponseDefaultTypeInternal;
extern LogoutResponseDefaultTypeInternal _LogoutResponse_default_instance_;
class PerformanceTestReq;
struct PerformanceTestReqDefaultTypeInternal;
extern PerformanceTestReqDefaultTypeInternal _PerformanceTestReq_default_instance_;
class PerformanceTestRes;
struct PerformanceTestResDefaultTypeInternal;
extern PerformanceTestResDefaultTypeInternal _PerformanceTestRes_default_instance_;
class Role;
struct RoleDefaultTypeInternal;
extern RoleDefaultTypeInternal _Role_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::EchoReq* Arena::CreateMaybeMessage<::EchoReq>(Arena*);
template<> ::IntIntProto* Arena::CreateMaybeMessage<::IntIntProto>(Arena*);
template<> ::ItemProto* Arena::CreateMaybeMessage<::ItemProto>(Arena*);
template<> ::LoginRequest* Arena::CreateMaybeMessage<::LoginRequest>(Arena*);
template<> ::LoginResponse* Arena::CreateMaybeMessage<::LoginResponse>(Arena*);
template<> ::LogoutRequest* Arena::CreateMaybeMessage<::LogoutRequest>(Arena*);
template<> ::LogoutResponse* Arena::CreateMaybeMessage<::LogoutResponse>(Arena*);
template<> ::PerformanceTestReq* Arena::CreateMaybeMessage<::PerformanceTestReq>(Arena*);
template<> ::PerformanceTestRes* Arena::CreateMaybeMessage<::PerformanceTestRes>(Arena*);
template<> ::Role* Arena::CreateMaybeMessage<::Role>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class IntIntProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:IntIntProto) */ {
 public:
  inline IntIntProto() : IntIntProto(nullptr) {}
  ~IntIntProto() override;
  explicit PROTOBUF_CONSTEXPR IntIntProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IntIntProto(const IntIntProto& from);
  IntIntProto(IntIntProto&& from) noexcept
    : IntIntProto() {
    *this = ::std::move(from);
  }

  inline IntIntProto& operator=(const IntIntProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline IntIntProto& operator=(IntIntProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IntIntProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const IntIntProto* internal_default_instance() {
    return reinterpret_cast<const IntIntProto*>(
               &_IntIntProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IntIntProto& a, IntIntProto& b) {
    a.Swap(&b);
  }
  inline void Swap(IntIntProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IntIntProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IntIntProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IntIntProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IntIntProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IntIntProto& from) {
    IntIntProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IntIntProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IntIntProto";
  }
  protected:
  explicit IntIntProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIntValue1FieldNumber = 1,
    kIntValue2FieldNumber = 2,
  };
  // int32 intValue1 = 1;
  void clear_intvalue1();
  int32_t intvalue1() const;
  void set_intvalue1(int32_t value);
  private:
  int32_t _internal_intvalue1() const;
  void _internal_set_intvalue1(int32_t value);
  public:

  // int32 intValue2 = 2;
  void clear_intvalue2();
  int32_t intvalue2() const;
  void set_intvalue2(int32_t value);
  private:
  int32_t _internal_intvalue2() const;
  void _internal_set_intvalue2(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:IntIntProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t intvalue1_;
    int32_t intvalue2_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoTask_2eproto;
};
// -------------------------------------------------------------------

class Role final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Role) */ {
 public:
  inline Role() : Role(nullptr) {}
  ~Role() override;
  explicit PROTOBUF_CONSTEXPR Role(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Role(const Role& from);
  Role(Role&& from) noexcept
    : Role() {
    *this = ::std::move(from);
  }

  inline Role& operator=(const Role& from) {
    CopyFrom(from);
    return *this;
  }
  inline Role& operator=(Role&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Role& default_instance() {
    return *internal_default_instance();
  }
  static inline const Role* internal_default_instance() {
    return reinterpret_cast<const Role*>(
               &_Role_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Role& a, Role& b) {
    a.Swap(&b);
  }
  inline void Swap(Role* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Role* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Role* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Role>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Role& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Role& from) {
    Role::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Role* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Role";
  }
  protected:
  explicit Role(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Role)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    int64_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoTask_2eproto;
};
// -------------------------------------------------------------------

class ItemProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ItemProto) */ {
 public:
  inline ItemProto() : ItemProto(nullptr) {}
  ~ItemProto() override;
  explicit PROTOBUF_CONSTEXPR ItemProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ItemProto(const ItemProto& from);
  ItemProto(ItemProto&& from) noexcept
    : ItemProto() {
    *this = ::std::move(from);
  }

  inline ItemProto& operator=(const ItemProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline ItemProto& operator=(ItemProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ItemProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const ItemProto* internal_default_instance() {
    return reinterpret_cast<const ItemProto*>(
               &_ItemProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ItemProto& a, ItemProto& b) {
    a.Swap(&b);
  }
  inline void Swap(ItemProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ItemProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ItemProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ItemProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ItemProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ItemProto& from) {
    ItemProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ItemProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ItemProto";
  }
  protected:
  explicit ItemProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemIdFieldNumber = 1,
    kCountFieldNumber = 2,
  };
  // int32 itemId = 1;
  void clear_itemid();
  int32_t itemid() const;
  void set_itemid(int32_t value);
  private:
  int32_t _internal_itemid() const;
  void _internal_set_itemid(int32_t value);
  public:

  // int32 count = 2;
  void clear_count();
  int32_t count() const;
  void set_count(int32_t value);
  private:
  int32_t _internal_count() const;
  void _internal_set_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ItemProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t itemid_;
    int32_t count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoTask_2eproto;
};
// -------------------------------------------------------------------

class LoginRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LoginRequest) */ {
 public:
  inline LoginRequest() : LoginRequest(nullptr) {}
  ~LoginRequest() override;
  explicit PROTOBUF_CONSTEXPR LoginRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginRequest(const LoginRequest& from);
  LoginRequest(LoginRequest&& from) noexcept
    : LoginRequest() {
    *this = ::std::move(from);
  }

  inline LoginRequest& operator=(const LoginRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginRequest& operator=(LoginRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginRequest* internal_default_instance() {
    return reinterpret_cast<const LoginRequest*>(
               &_LoginRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(LoginRequest& a, LoginRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LoginRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LoginRequest& from) {
    LoginRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LoginRequest";
  }
  protected:
  explicit LoginRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLoginTokenFieldNumber = 3,
    kAccountIdFieldNumber = 1,
    kRoleIdFieldNumber = 2,
    kGameTicketFieldNumber = 4,
    kServerIdFieldNumber = 5,
  };
  // string loginToken = 3;
  void clear_logintoken();
  const std::string& logintoken() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_logintoken(ArgT0&& arg0, ArgT... args);
  std::string* mutable_logintoken();
  PROTOBUF_NODISCARD std::string* release_logintoken();
  void set_allocated_logintoken(std::string* logintoken);
  private:
  const std::string& _internal_logintoken() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_logintoken(const std::string& value);
  std::string* _internal_mutable_logintoken();
  public:

  // int64 accountId = 1;
  void clear_accountid();
  int64_t accountid() const;
  void set_accountid(int64_t value);
  private:
  int64_t _internal_accountid() const;
  void _internal_set_accountid(int64_t value);
  public:

  // int64 roleId = 2;
  void clear_roleid();
  int64_t roleid() const;
  void set_roleid(int64_t value);
  private:
  int64_t _internal_roleid() const;
  void _internal_set_roleid(int64_t value);
  public:

  // int32 gameTicket = 4;
  void clear_gameticket();
  int32_t gameticket() const;
  void set_gameticket(int32_t value);
  private:
  int32_t _internal_gameticket() const;
  void _internal_set_gameticket(int32_t value);
  public:

  // int32 serverId = 5;
  void clear_serverid();
  int32_t serverid() const;
  void set_serverid(int32_t value);
  private:
  int32_t _internal_serverid() const;
  void _internal_set_serverid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:LoginRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr logintoken_;
    int64_t accountid_;
    int64_t roleid_;
    int32_t gameticket_;
    int32_t serverid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoTask_2eproto;
};
// -------------------------------------------------------------------

class LoginResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LoginResponse) */ {
 public:
  inline LoginResponse() : LoginResponse(nullptr) {}
  ~LoginResponse() override;
  explicit PROTOBUF_CONSTEXPR LoginResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginResponse(const LoginResponse& from);
  LoginResponse(LoginResponse&& from) noexcept
    : LoginResponse() {
    *this = ::std::move(from);
  }

  inline LoginResponse& operator=(const LoginResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginResponse& operator=(LoginResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginResponse* internal_default_instance() {
    return reinterpret_cast<const LoginResponse*>(
               &_LoginResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(LoginResponse& a, LoginResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LoginResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LoginResponse& from) {
    LoginResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LoginResponse";
  }
  protected:
  explicit LoginResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerTimeFieldNumber = 2,
    kRoleIdFieldNumber = 3,
    kErrorCodeFieldNumber = 1,
  };
  // int64 serverTime = 2;
  void clear_servertime();
  int64_t servertime() const;
  void set_servertime(int64_t value);
  private:
  int64_t _internal_servertime() const;
  void _internal_set_servertime(int64_t value);
  public:

  // int64 roleId = 3;
  void clear_roleid();
  int64_t roleid() const;
  void set_roleid(int64_t value);
  private:
  int64_t _internal_roleid() const;
  void _internal_set_roleid(int64_t value);
  public:

  // int32 errorCode = 1;
  void clear_errorcode();
  int32_t errorcode() const;
  void set_errorcode(int32_t value);
  private:
  int32_t _internal_errorcode() const;
  void _internal_set_errorcode(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:LoginResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t servertime_;
    int64_t roleid_;
    int32_t errorcode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoTask_2eproto;
};
// -------------------------------------------------------------------

class LogoutRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LogoutRequest) */ {
 public:
  inline LogoutRequest() : LogoutRequest(nullptr) {}
  ~LogoutRequest() override;
  explicit PROTOBUF_CONSTEXPR LogoutRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogoutRequest(const LogoutRequest& from);
  LogoutRequest(LogoutRequest&& from) noexcept
    : LogoutRequest() {
    *this = ::std::move(from);
  }

  inline LogoutRequest& operator=(const LogoutRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogoutRequest& operator=(LogoutRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogoutRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogoutRequest* internal_default_instance() {
    return reinterpret_cast<const LogoutRequest*>(
               &_LogoutRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(LogoutRequest& a, LogoutRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LogoutRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogoutRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogoutRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogoutRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogoutRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogoutRequest& from) {
    LogoutRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogoutRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LogoutRequest";
  }
  protected:
  explicit LogoutRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionIdFieldNumber = 1,
  };
  // int64 sessionId = 1;
  void clear_sessionid();
  int64_t sessionid() const;
  void set_sessionid(int64_t value);
  private:
  int64_t _internal_sessionid() const;
  void _internal_set_sessionid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:LogoutRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t sessionid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoTask_2eproto;
};
// -------------------------------------------------------------------

class LogoutResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LogoutResponse) */ {
 public:
  inline LogoutResponse() : LogoutResponse(nullptr) {}
  ~LogoutResponse() override;
  explicit PROTOBUF_CONSTEXPR LogoutResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogoutResponse(const LogoutResponse& from);
  LogoutResponse(LogoutResponse&& from) noexcept
    : LogoutResponse() {
    *this = ::std::move(from);
  }

  inline LogoutResponse& operator=(const LogoutResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogoutResponse& operator=(LogoutResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogoutResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogoutResponse* internal_default_instance() {
    return reinterpret_cast<const LogoutResponse*>(
               &_LogoutResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(LogoutResponse& a, LogoutResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(LogoutResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogoutResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogoutResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogoutResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogoutResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogoutResponse& from) {
    LogoutResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogoutResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LogoutResponse";
  }
  protected:
  explicit LogoutResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorCodeFieldNumber = 1,
  };
  // int32 errorCode = 1;
  void clear_errorcode();
  int32_t errorcode() const;
  void set_errorcode(int32_t value);
  private:
  int32_t _internal_errorcode() const;
  void _internal_set_errorcode(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:LogoutResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t errorcode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoTask_2eproto;
};
// -------------------------------------------------------------------

class PerformanceTestReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PerformanceTestReq) */ {
 public:
  inline PerformanceTestReq() : PerformanceTestReq(nullptr) {}
  ~PerformanceTestReq() override;
  explicit PROTOBUF_CONSTEXPR PerformanceTestReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PerformanceTestReq(const PerformanceTestReq& from);
  PerformanceTestReq(PerformanceTestReq&& from) noexcept
    : PerformanceTestReq() {
    *this = ::std::move(from);
  }

  inline PerformanceTestReq& operator=(const PerformanceTestReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline PerformanceTestReq& operator=(PerformanceTestReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PerformanceTestReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const PerformanceTestReq* internal_default_instance() {
    return reinterpret_cast<const PerformanceTestReq*>(
               &_PerformanceTestReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(PerformanceTestReq& a, PerformanceTestReq& b) {
    a.Swap(&b);
  }
  inline void Swap(PerformanceTestReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PerformanceTestReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PerformanceTestReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PerformanceTestReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PerformanceTestReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PerformanceTestReq& from) {
    PerformanceTestReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerformanceTestReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PerformanceTestReq";
  }
  protected:
  explicit PerformanceTestReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSomeBodyFieldNumber = 2,
    kSomeIdFieldNumber = 1,
  };
  // string someBody = 2;
  void clear_somebody();
  const std::string& somebody() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_somebody(ArgT0&& arg0, ArgT... args);
  std::string* mutable_somebody();
  PROTOBUF_NODISCARD std::string* release_somebody();
  void set_allocated_somebody(std::string* somebody);
  private:
  const std::string& _internal_somebody() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_somebody(const std::string& value);
  std::string* _internal_mutable_somebody();
  public:

  // int64 someId = 1;
  void clear_someid();
  int64_t someid() const;
  void set_someid(int64_t value);
  private:
  int64_t _internal_someid() const;
  void _internal_set_someid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PerformanceTestReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr somebody_;
    int64_t someid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoTask_2eproto;
};
// -------------------------------------------------------------------

class PerformanceTestRes final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PerformanceTestRes) */ {
 public:
  inline PerformanceTestRes() : PerformanceTestRes(nullptr) {}
  ~PerformanceTestRes() override;
  explicit PROTOBUF_CONSTEXPR PerformanceTestRes(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PerformanceTestRes(const PerformanceTestRes& from);
  PerformanceTestRes(PerformanceTestRes&& from) noexcept
    : PerformanceTestRes() {
    *this = ::std::move(from);
  }

  inline PerformanceTestRes& operator=(const PerformanceTestRes& from) {
    CopyFrom(from);
    return *this;
  }
  inline PerformanceTestRes& operator=(PerformanceTestRes&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PerformanceTestRes& default_instance() {
    return *internal_default_instance();
  }
  static inline const PerformanceTestRes* internal_default_instance() {
    return reinterpret_cast<const PerformanceTestRes*>(
               &_PerformanceTestRes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(PerformanceTestRes& a, PerformanceTestRes& b) {
    a.Swap(&b);
  }
  inline void Swap(PerformanceTestRes* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PerformanceTestRes* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PerformanceTestRes* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PerformanceTestRes>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PerformanceTestRes& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PerformanceTestRes& from) {
    PerformanceTestRes::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerformanceTestRes* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PerformanceTestRes";
  }
  protected:
  explicit PerformanceTestRes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResBodyFieldNumber = 2,
    kSomeIdFieldNumber = 1,
    kSomeIdAddFieldNumber = 3,
  };
  // string resBody = 2;
  void clear_resbody();
  const std::string& resbody() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_resbody(ArgT0&& arg0, ArgT... args);
  std::string* mutable_resbody();
  PROTOBUF_NODISCARD std::string* release_resbody();
  void set_allocated_resbody(std::string* resbody);
  private:
  const std::string& _internal_resbody() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_resbody(const std::string& value);
  std::string* _internal_mutable_resbody();
  public:

  // int64 someId = 1;
  void clear_someid();
  int64_t someid() const;
  void set_someid(int64_t value);
  private:
  int64_t _internal_someid() const;
  void _internal_set_someid(int64_t value);
  public:

  // int64 someIdAdd = 3;
  void clear_someidadd();
  int64_t someidadd() const;
  void set_someidadd(int64_t value);
  private:
  int64_t _internal_someidadd() const;
  void _internal_set_someidadd(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PerformanceTestRes)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr resbody_;
    int64_t someid_;
    int64_t someidadd_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoTask_2eproto;
};
// -------------------------------------------------------------------

class EchoReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:EchoReq) */ {
 public:
  inline EchoReq() : EchoReq(nullptr) {}
  ~EchoReq() override;
  explicit PROTOBUF_CONSTEXPR EchoReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EchoReq(const EchoReq& from);
  EchoReq(EchoReq&& from) noexcept
    : EchoReq() {
    *this = ::std::move(from);
  }

  inline EchoReq& operator=(const EchoReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline EchoReq& operator=(EchoReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EchoReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const EchoReq* internal_default_instance() {
    return reinterpret_cast<const EchoReq*>(
               &_EchoReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(EchoReq& a, EchoReq& b) {
    a.Swap(&b);
  }
  inline void Swap(EchoReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EchoReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EchoReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EchoReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EchoReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EchoReq& from) {
    EchoReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EchoReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "EchoReq";
  }
  protected:
  explicit EchoReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestBodyFieldNumber = 1,
    kSomeIdFieldNumber = 2,
  };
  // string requestBody = 1;
  void clear_requestbody();
  const std::string& requestbody() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_requestbody(ArgT0&& arg0, ArgT... args);
  std::string* mutable_requestbody();
  PROTOBUF_NODISCARD std::string* release_requestbody();
  void set_allocated_requestbody(std::string* requestbody);
  private:
  const std::string& _internal_requestbody() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_requestbody(const std::string& value);
  std::string* _internal_mutable_requestbody();
  public:

  // int64 someId = 2;
  void clear_someid();
  int64_t someid() const;
  void set_someid(int64_t value);
  private:
  int64_t _internal_someid() const;
  void _internal_set_someid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:EchoReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr requestbody_;
    int64_t someid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoTask_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IntIntProto

// int32 intValue1 = 1;
inline void IntIntProto::clear_intvalue1() {
  _impl_.intvalue1_ = 0;
}
inline int32_t IntIntProto::_internal_intvalue1() const {
  return _impl_.intvalue1_;
}
inline int32_t IntIntProto::intvalue1() const {
  // @@protoc_insertion_point(field_get:IntIntProto.intValue1)
  return _internal_intvalue1();
}
inline void IntIntProto::_internal_set_intvalue1(int32_t value) {
  
  _impl_.intvalue1_ = value;
}
inline void IntIntProto::set_intvalue1(int32_t value) {
  _internal_set_intvalue1(value);
  // @@protoc_insertion_point(field_set:IntIntProto.intValue1)
}

// int32 intValue2 = 2;
inline void IntIntProto::clear_intvalue2() {
  _impl_.intvalue2_ = 0;
}
inline int32_t IntIntProto::_internal_intvalue2() const {
  return _impl_.intvalue2_;
}
inline int32_t IntIntProto::intvalue2() const {
  // @@protoc_insertion_point(field_get:IntIntProto.intValue2)
  return _internal_intvalue2();
}
inline void IntIntProto::_internal_set_intvalue2(int32_t value) {
  
  _impl_.intvalue2_ = value;
}
inline void IntIntProto::set_intvalue2(int32_t value) {
  _internal_set_intvalue2(value);
  // @@protoc_insertion_point(field_set:IntIntProto.intValue2)
}

// -------------------------------------------------------------------

// Role

// int64 id = 1;
inline void Role::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t Role::_internal_id() const {
  return _impl_.id_;
}
inline int64_t Role::id() const {
  // @@protoc_insertion_point(field_get:Role.id)
  return _internal_id();
}
inline void Role::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void Role::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Role.id)
}

// string name = 2;
inline void Role::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Role::name() const {
  // @@protoc_insertion_point(field_get:Role.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Role::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Role.name)
}
inline std::string* Role::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Role.name)
  return _s;
}
inline const std::string& Role::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Role::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Role::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Role::release_name() {
  // @@protoc_insertion_point(field_release:Role.name)
  return _impl_.name_.Release();
}
inline void Role::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Role.name)
}

// -------------------------------------------------------------------

// ItemProto

// int32 itemId = 1;
inline void ItemProto::clear_itemid() {
  _impl_.itemid_ = 0;
}
inline int32_t ItemProto::_internal_itemid() const {
  return _impl_.itemid_;
}
inline int32_t ItemProto::itemid() const {
  // @@protoc_insertion_point(field_get:ItemProto.itemId)
  return _internal_itemid();
}
inline void ItemProto::_internal_set_itemid(int32_t value) {
  
  _impl_.itemid_ = value;
}
inline void ItemProto::set_itemid(int32_t value) {
  _internal_set_itemid(value);
  // @@protoc_insertion_point(field_set:ItemProto.itemId)
}

// int32 count = 2;
inline void ItemProto::clear_count() {
  _impl_.count_ = 0;
}
inline int32_t ItemProto::_internal_count() const {
  return _impl_.count_;
}
inline int32_t ItemProto::count() const {
  // @@protoc_insertion_point(field_get:ItemProto.count)
  return _internal_count();
}
inline void ItemProto::_internal_set_count(int32_t value) {
  
  _impl_.count_ = value;
}
inline void ItemProto::set_count(int32_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:ItemProto.count)
}

// -------------------------------------------------------------------

// LoginRequest

// int64 accountId = 1;
inline void LoginRequest::clear_accountid() {
  _impl_.accountid_ = int64_t{0};
}
inline int64_t LoginRequest::_internal_accountid() const {
  return _impl_.accountid_;
}
inline int64_t LoginRequest::accountid() const {
  // @@protoc_insertion_point(field_get:LoginRequest.accountId)
  return _internal_accountid();
}
inline void LoginRequest::_internal_set_accountid(int64_t value) {
  
  _impl_.accountid_ = value;
}
inline void LoginRequest::set_accountid(int64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:LoginRequest.accountId)
}

// int64 roleId = 2;
inline void LoginRequest::clear_roleid() {
  _impl_.roleid_ = int64_t{0};
}
inline int64_t LoginRequest::_internal_roleid() const {
  return _impl_.roleid_;
}
inline int64_t LoginRequest::roleid() const {
  // @@protoc_insertion_point(field_get:LoginRequest.roleId)
  return _internal_roleid();
}
inline void LoginRequest::_internal_set_roleid(int64_t value) {
  
  _impl_.roleid_ = value;
}
inline void LoginRequest::set_roleid(int64_t value) {
  _internal_set_roleid(value);
  // @@protoc_insertion_point(field_set:LoginRequest.roleId)
}

// string loginToken = 3;
inline void LoginRequest::clear_logintoken() {
  _impl_.logintoken_.ClearToEmpty();
}
inline const std::string& LoginRequest::logintoken() const {
  // @@protoc_insertion_point(field_get:LoginRequest.loginToken)
  return _internal_logintoken();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginRequest::set_logintoken(ArgT0&& arg0, ArgT... args) {
 
 _impl_.logintoken_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:LoginRequest.loginToken)
}
inline std::string* LoginRequest::mutable_logintoken() {
  std::string* _s = _internal_mutable_logintoken();
  // @@protoc_insertion_point(field_mutable:LoginRequest.loginToken)
  return _s;
}
inline const std::string& LoginRequest::_internal_logintoken() const {
  return _impl_.logintoken_.Get();
}
inline void LoginRequest::_internal_set_logintoken(const std::string& value) {
  
  _impl_.logintoken_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginRequest::_internal_mutable_logintoken() {
  
  return _impl_.logintoken_.Mutable(GetArenaForAllocation());
}
inline std::string* LoginRequest::release_logintoken() {
  // @@protoc_insertion_point(field_release:LoginRequest.loginToken)
  return _impl_.logintoken_.Release();
}
inline void LoginRequest::set_allocated_logintoken(std::string* logintoken) {
  if (logintoken != nullptr) {
    
  } else {
    
  }
  _impl_.logintoken_.SetAllocated(logintoken, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.logintoken_.IsDefault()) {
    _impl_.logintoken_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:LoginRequest.loginToken)
}

// int32 gameTicket = 4;
inline void LoginRequest::clear_gameticket() {
  _impl_.gameticket_ = 0;
}
inline int32_t LoginRequest::_internal_gameticket() const {
  return _impl_.gameticket_;
}
inline int32_t LoginRequest::gameticket() const {
  // @@protoc_insertion_point(field_get:LoginRequest.gameTicket)
  return _internal_gameticket();
}
inline void LoginRequest::_internal_set_gameticket(int32_t value) {
  
  _impl_.gameticket_ = value;
}
inline void LoginRequest::set_gameticket(int32_t value) {
  _internal_set_gameticket(value);
  // @@protoc_insertion_point(field_set:LoginRequest.gameTicket)
}

// int32 serverId = 5;
inline void LoginRequest::clear_serverid() {
  _impl_.serverid_ = 0;
}
inline int32_t LoginRequest::_internal_serverid() const {
  return _impl_.serverid_;
}
inline int32_t LoginRequest::serverid() const {
  // @@protoc_insertion_point(field_get:LoginRequest.serverId)
  return _internal_serverid();
}
inline void LoginRequest::_internal_set_serverid(int32_t value) {
  
  _impl_.serverid_ = value;
}
inline void LoginRequest::set_serverid(int32_t value) {
  _internal_set_serverid(value);
  // @@protoc_insertion_point(field_set:LoginRequest.serverId)
}

// -------------------------------------------------------------------

// LoginResponse

// int32 errorCode = 1;
inline void LoginResponse::clear_errorcode() {
  _impl_.errorcode_ = 0;
}
inline int32_t LoginResponse::_internal_errorcode() const {
  return _impl_.errorcode_;
}
inline int32_t LoginResponse::errorcode() const {
  // @@protoc_insertion_point(field_get:LoginResponse.errorCode)
  return _internal_errorcode();
}
inline void LoginResponse::_internal_set_errorcode(int32_t value) {
  
  _impl_.errorcode_ = value;
}
inline void LoginResponse::set_errorcode(int32_t value) {
  _internal_set_errorcode(value);
  // @@protoc_insertion_point(field_set:LoginResponse.errorCode)
}

// int64 serverTime = 2;
inline void LoginResponse::clear_servertime() {
  _impl_.servertime_ = int64_t{0};
}
inline int64_t LoginResponse::_internal_servertime() const {
  return _impl_.servertime_;
}
inline int64_t LoginResponse::servertime() const {
  // @@protoc_insertion_point(field_get:LoginResponse.serverTime)
  return _internal_servertime();
}
inline void LoginResponse::_internal_set_servertime(int64_t value) {
  
  _impl_.servertime_ = value;
}
inline void LoginResponse::set_servertime(int64_t value) {
  _internal_set_servertime(value);
  // @@protoc_insertion_point(field_set:LoginResponse.serverTime)
}

// int64 roleId = 3;
inline void LoginResponse::clear_roleid() {
  _impl_.roleid_ = int64_t{0};
}
inline int64_t LoginResponse::_internal_roleid() const {
  return _impl_.roleid_;
}
inline int64_t LoginResponse::roleid() const {
  // @@protoc_insertion_point(field_get:LoginResponse.roleId)
  return _internal_roleid();
}
inline void LoginResponse::_internal_set_roleid(int64_t value) {
  
  _impl_.roleid_ = value;
}
inline void LoginResponse::set_roleid(int64_t value) {
  _internal_set_roleid(value);
  // @@protoc_insertion_point(field_set:LoginResponse.roleId)
}

// -------------------------------------------------------------------

// LogoutRequest

// int64 sessionId = 1;
inline void LogoutRequest::clear_sessionid() {
  _impl_.sessionid_ = int64_t{0};
}
inline int64_t LogoutRequest::_internal_sessionid() const {
  return _impl_.sessionid_;
}
inline int64_t LogoutRequest::sessionid() const {
  // @@protoc_insertion_point(field_get:LogoutRequest.sessionId)
  return _internal_sessionid();
}
inline void LogoutRequest::_internal_set_sessionid(int64_t value) {
  
  _impl_.sessionid_ = value;
}
inline void LogoutRequest::set_sessionid(int64_t value) {
  _internal_set_sessionid(value);
  // @@protoc_insertion_point(field_set:LogoutRequest.sessionId)
}

// -------------------------------------------------------------------

// LogoutResponse

// int32 errorCode = 1;
inline void LogoutResponse::clear_errorcode() {
  _impl_.errorcode_ = 0;
}
inline int32_t LogoutResponse::_internal_errorcode() const {
  return _impl_.errorcode_;
}
inline int32_t LogoutResponse::errorcode() const {
  // @@protoc_insertion_point(field_get:LogoutResponse.errorCode)
  return _internal_errorcode();
}
inline void LogoutResponse::_internal_set_errorcode(int32_t value) {
  
  _impl_.errorcode_ = value;
}
inline void LogoutResponse::set_errorcode(int32_t value) {
  _internal_set_errorcode(value);
  // @@protoc_insertion_point(field_set:LogoutResponse.errorCode)
}

// -------------------------------------------------------------------

// PerformanceTestReq

// int64 someId = 1;
inline void PerformanceTestReq::clear_someid() {
  _impl_.someid_ = int64_t{0};
}
inline int64_t PerformanceTestReq::_internal_someid() const {
  return _impl_.someid_;
}
inline int64_t PerformanceTestReq::someid() const {
  // @@protoc_insertion_point(field_get:PerformanceTestReq.someId)
  return _internal_someid();
}
inline void PerformanceTestReq::_internal_set_someid(int64_t value) {
  
  _impl_.someid_ = value;
}
inline void PerformanceTestReq::set_someid(int64_t value) {
  _internal_set_someid(value);
  // @@protoc_insertion_point(field_set:PerformanceTestReq.someId)
}

// string someBody = 2;
inline void PerformanceTestReq::clear_somebody() {
  _impl_.somebody_.ClearToEmpty();
}
inline const std::string& PerformanceTestReq::somebody() const {
  // @@protoc_insertion_point(field_get:PerformanceTestReq.someBody)
  return _internal_somebody();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PerformanceTestReq::set_somebody(ArgT0&& arg0, ArgT... args) {
 
 _impl_.somebody_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PerformanceTestReq.someBody)
}
inline std::string* PerformanceTestReq::mutable_somebody() {
  std::string* _s = _internal_mutable_somebody();
  // @@protoc_insertion_point(field_mutable:PerformanceTestReq.someBody)
  return _s;
}
inline const std::string& PerformanceTestReq::_internal_somebody() const {
  return _impl_.somebody_.Get();
}
inline void PerformanceTestReq::_internal_set_somebody(const std::string& value) {
  
  _impl_.somebody_.Set(value, GetArenaForAllocation());
}
inline std::string* PerformanceTestReq::_internal_mutable_somebody() {
  
  return _impl_.somebody_.Mutable(GetArenaForAllocation());
}
inline std::string* PerformanceTestReq::release_somebody() {
  // @@protoc_insertion_point(field_release:PerformanceTestReq.someBody)
  return _impl_.somebody_.Release();
}
inline void PerformanceTestReq::set_allocated_somebody(std::string* somebody) {
  if (somebody != nullptr) {
    
  } else {
    
  }
  _impl_.somebody_.SetAllocated(somebody, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.somebody_.IsDefault()) {
    _impl_.somebody_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PerformanceTestReq.someBody)
}

// -------------------------------------------------------------------

// PerformanceTestRes

// int64 someId = 1;
inline void PerformanceTestRes::clear_someid() {
  _impl_.someid_ = int64_t{0};
}
inline int64_t PerformanceTestRes::_internal_someid() const {
  return _impl_.someid_;
}
inline int64_t PerformanceTestRes::someid() const {
  // @@protoc_insertion_point(field_get:PerformanceTestRes.someId)
  return _internal_someid();
}
inline void PerformanceTestRes::_internal_set_someid(int64_t value) {
  
  _impl_.someid_ = value;
}
inline void PerformanceTestRes::set_someid(int64_t value) {
  _internal_set_someid(value);
  // @@protoc_insertion_point(field_set:PerformanceTestRes.someId)
}

// string resBody = 2;
inline void PerformanceTestRes::clear_resbody() {
  _impl_.resbody_.ClearToEmpty();
}
inline const std::string& PerformanceTestRes::resbody() const {
  // @@protoc_insertion_point(field_get:PerformanceTestRes.resBody)
  return _internal_resbody();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PerformanceTestRes::set_resbody(ArgT0&& arg0, ArgT... args) {
 
 _impl_.resbody_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PerformanceTestRes.resBody)
}
inline std::string* PerformanceTestRes::mutable_resbody() {
  std::string* _s = _internal_mutable_resbody();
  // @@protoc_insertion_point(field_mutable:PerformanceTestRes.resBody)
  return _s;
}
inline const std::string& PerformanceTestRes::_internal_resbody() const {
  return _impl_.resbody_.Get();
}
inline void PerformanceTestRes::_internal_set_resbody(const std::string& value) {
  
  _impl_.resbody_.Set(value, GetArenaForAllocation());
}
inline std::string* PerformanceTestRes::_internal_mutable_resbody() {
  
  return _impl_.resbody_.Mutable(GetArenaForAllocation());
}
inline std::string* PerformanceTestRes::release_resbody() {
  // @@protoc_insertion_point(field_release:PerformanceTestRes.resBody)
  return _impl_.resbody_.Release();
}
inline void PerformanceTestRes::set_allocated_resbody(std::string* resbody) {
  if (resbody != nullptr) {
    
  } else {
    
  }
  _impl_.resbody_.SetAllocated(resbody, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.resbody_.IsDefault()) {
    _impl_.resbody_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PerformanceTestRes.resBody)
}

// int64 someIdAdd = 3;
inline void PerformanceTestRes::clear_someidadd() {
  _impl_.someidadd_ = int64_t{0};
}
inline int64_t PerformanceTestRes::_internal_someidadd() const {
  return _impl_.someidadd_;
}
inline int64_t PerformanceTestRes::someidadd() const {
  // @@protoc_insertion_point(field_get:PerformanceTestRes.someIdAdd)
  return _internal_someidadd();
}
inline void PerformanceTestRes::_internal_set_someidadd(int64_t value) {
  
  _impl_.someidadd_ = value;
}
inline void PerformanceTestRes::set_someidadd(int64_t value) {
  _internal_set_someidadd(value);
  // @@protoc_insertion_point(field_set:PerformanceTestRes.someIdAdd)
}

// -------------------------------------------------------------------

// EchoReq

// string requestBody = 1;
inline void EchoReq::clear_requestbody() {
  _impl_.requestbody_.ClearToEmpty();
}
inline const std::string& EchoReq::requestbody() const {
  // @@protoc_insertion_point(field_get:EchoReq.requestBody)
  return _internal_requestbody();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EchoReq::set_requestbody(ArgT0&& arg0, ArgT... args) {
 
 _impl_.requestbody_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:EchoReq.requestBody)
}
inline std::string* EchoReq::mutable_requestbody() {
  std::string* _s = _internal_mutable_requestbody();
  // @@protoc_insertion_point(field_mutable:EchoReq.requestBody)
  return _s;
}
inline const std::string& EchoReq::_internal_requestbody() const {
  return _impl_.requestbody_.Get();
}
inline void EchoReq::_internal_set_requestbody(const std::string& value) {
  
  _impl_.requestbody_.Set(value, GetArenaForAllocation());
}
inline std::string* EchoReq::_internal_mutable_requestbody() {
  
  return _impl_.requestbody_.Mutable(GetArenaForAllocation());
}
inline std::string* EchoReq::release_requestbody() {
  // @@protoc_insertion_point(field_release:EchoReq.requestBody)
  return _impl_.requestbody_.Release();
}
inline void EchoReq::set_allocated_requestbody(std::string* requestbody) {
  if (requestbody != nullptr) {
    
  } else {
    
  }
  _impl_.requestbody_.SetAllocated(requestbody, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.requestbody_.IsDefault()) {
    _impl_.requestbody_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:EchoReq.requestBody)
}

// int64 someId = 2;
inline void EchoReq::clear_someid() {
  _impl_.someid_ = int64_t{0};
}
inline int64_t EchoReq::_internal_someid() const {
  return _impl_.someid_;
}
inline int64_t EchoReq::someid() const {
  // @@protoc_insertion_point(field_get:EchoReq.someId)
  return _internal_someid();
}
inline void EchoReq::_internal_set_someid(int64_t value) {
  
  _impl_.someid_ = value;
}
inline void EchoReq::set_someid(int64_t value) {
  _internal_set_someid(value);
  // @@protoc_insertion_point(field_set:EchoReq.someId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ProtoTask_2eproto
