[server]
name = "cgame.V1"
type = 3
port = 27080
tcp-port = 27081
group-id = 0
max-player-count = 20000
io-thread = 1

[discover]
server_nodes = "http://localhost:2379;http://localhost:2379"
watch-servers = ["game.V1", "mmo-world.V1"]

[mongodb]
ip = "localhost"
port = 6379
username = "admin"
password = "admin"

[redis]
ip = "localhost"
port = 6379
username = "admin"
password = "admin"